quayio: Add export compliance service to Red Hat SSO (PROJQUAY-2056)
quay/quay pull request #1239
Opened 2022-04-11 17:47 UTC by jonathankingfc

- Add FEATURE_EXPORT_COMPLIANCE to config schema
- Add call to export compliance service during OAuth workflow when feature is enabled

2022-04-12 18:07 UTC, syed approved these changes

2022-04-12 18:07 UTC, syed commented on endpoints/oauth/login.py
> +                "https://export-compliance.dev.api.redhat.com/v1/screening",
make this a const/config?

2022-04-14 19:36 UTC, kleesc commented
@jonathankingfc Are there any references to the external api that this is hitting?

2022-04-14 19:58 UTC, jonathankingfc commented on endpoints/oauth/login.py
> +                app.config.get("EXPORT_COMPLIANCE_ENDPOINT"),
@kleesc This is the endpoint, it is set as a config variable which is in the staging config since we don't want to expose it publicly.

2022-04-14 20:54 UTC, syed requested changes

2022-04-14 20:54 UTC, syed commented on endpoints/oauth/login.py
> +            result = requests.post(
@jonathankingfc is there a timeout here? I think the default action is to wait indefinitely

2022-04-18 16:40 UTC, syed approved these changes

2022-04-18 16:45 UTC, merged