logs: add audit log events for login/logout to Quay (PROJQUAY-2344)
quay/quay pull request #1866
Opened 2023-05-05 16:49 UTC by dmesser

Based on @harishsurf 's work in #1822 this is adding audit events for :

- login/ logout of quay (e.g. via the Web UI)
- login via registry docker v2/OCI protocol (e.g. via docker/podman CLI)

It also adds visualization in the current log view UI.

Note: No call is made to docker registry API during a logout from docker/podman CLI, hence no audit events are logged
Testing: verified with a local instance and database audit logging

<img width="1238" alt="Screenshot 2023-05-05 at 18 47 26" src="https://user-images.githubusercontent.com/12664117/236518450-a6ea2a88-7332-407f-899f-f3b899c2e47c.png">
<img width="1233" alt="Screenshot 2023-05-05 at 18 47 17" src="https://user-images.githubusercontent.com/12664117/236518457-b4aabe2f-6ddb-487c-a140-7d178590e210.png">

2023-05-10 13:50 UTC, harishsurf submitted a review, later dismissed
lgtm! the visualization is a nice touch :)

2023-05-16 14:06 UTC, harishsurf approved these changes

2023-05-16 17:55 UTC, dmage requested changes
`amd64` is failing, `make update-testdata` is required

2023-05-17 09:22 UTC, dmage approved these changes

2023-05-17 09:22 UTC, merged