api: allow manifests to be pulled by digest (PROJQUAY-5467)
quay/quay pull request #1877
Opened 2023-05-10 15:47 UTC by Marcusk19

Allow manifests referenced by dead tags to also be returned when looking up a manifest by digest. Lets newer versions of conftest push to quay, since it expects to be able to pull the conftest policy by digest when performing a push.

2023-05-11 08:52 UTC, flavianmissi commented
The need behind this change is unclear in this PR's description - would you mind expanding a little more on that @Marcusk19 ?

2023-05-11 09:52 UTC, dmage commented on endpoints/v2/manifest.py
> +            require_available=True,
allow_dead isn't exactly what you need. It'll return expired manifests, which is incorrect. Quay should always pretend that they are deleted.

Why do you need `require_available`? What happens if `require_available` isn't set?

2023-05-11 09:54 UTC, dmage requested changes
We need tests that confirm that this feature works as expected and Quay doesn't accidentally distribute expired images.

2023-05-11 20:15 UTC, Marcusk19 commented
@flavianmissi Yeah, this is supposed to address an error you get when [pushing an OPA policy to quay with conftest](https://www.conftest.dev/sharing/#pushing-to-an-oci-registry):
```
Error: push bundle: tagging: 
sha256:fae4613127bc35df711682c11e462dd9db2d2716dca45553c00669457eda91b1: not found 
```
It looks like this error occurs because manifests pushed by their digest are hidden by default, and conftest expects to be able to get that manifest to verify that it exists. This check was introduced in newer versions of conftest, which is why we didn't run into this issue in the past.

2023-05-11 20:26 UTC, Marcusk19 commented
@dmage Would the already existing registry tests cover this? It looks like there's [test_basic_push_by_manifest_digest](https://github.com/quay/quay/blob/d49dbd1515b3a17d21127b881461d333045552a5/test/registry/registry_tests.py#L204) that can be used to test pulling by digest and [test_attempt_pull_by_manifest_digest_for_deleted_tag](https://github.com/quay/quay/blob/d49dbd1515b3a17d21127b881461d333045552a5/test/registry/registry_tests.py#L2834) for testing expired images aren't returned

2023-05-15 08:30 UTC, flavianmissi commented
good job! lgtm but let's wait for others' feedback before landing this

2023-05-24 10:42 UTC, dmage commented
It makes temporary tags for manifests pushed by digest visible in UI.

<img width="1258" alt="Screenshot 2023-05-24 at 12 41 20" src="https://github.com/quay/quay/assets/443137/57df9759-0aba-4a0d-90b7-0c7a38f70469">

2023-05-25 09:43 UTC, flavianmissi commented
> @dmage I saw the discussion on slack mentioning using the digest to tag manifests pushed by digest. Should we do that instead of using these temp tags?

I like this solution.

@Marcusk19 I see you added a new flag for tagging by digest, is there a reason to not ditch the $temp-.* stuff completely? Will we break anything by doing that? 🤔

2023-05-25 09:44 UTC, flavianmissi commented
Unrelatedly, it looks like some of your tests are failing, please investigate if the failure is related to your change as it might affect the solution 🙏🏼

2023-05-25 18:16 UTC, Marcusk19 commented
@flavianmissi I think we're going back to the original approach, but instead of `allow_dead=True` a new boolean called `allow_hidden` is used to return the hidden but not expired tags. Should prevent the UI from becoming noisy with all the temp tags.

2023-05-26 10:05 UTC, dmage approved these changes

2023-05-26 11:55 UTC, flavianmissi approved these changes

2023-05-26 13:43 UTC, merged