endpoints(v1/superuser/config): adding a full config dump for compliance reasons (PROJQUAY-4559)
quay/quay pull request #3253
Opened 2024-09-24 08:39 UTC by michaelalang

This PR adds an new `/api/v1/superuser/config` endpoint that shall return all Flask configuration set to have compliance proof for various Security policies like PCI-DSS4.0. 

The response is structured in json format with main keys:

* config
* warning
* env
* schema

The `config` section returns all `config.yaml` and defaulted parameters used in the Flask App framework found in the `schema` section. 

The `warning` section returns all `config.yaml` and defaulted parameters not found in the `schema` section.

The `env` section returns all Environment variables configured.

The `schema` section returns the defined `utils.config.CONFIG_SCHEMA` types

*Known* sensitive fields are obfuscated with ten `*` and the original length of the field:
Example:
```
"password": "******** (8)" 
```

PR included sensitive classified key names:

* password
* db_uri
* secret_key
* access_key
* enable_health_debug_secret
* client_secret
* s3_access_key
* s3_secret_key
* cloudfront_key_id
* sts_user_access_key
* sts_user_secret_key
* ldap_admin_passwd
* page_token_key
* security_scanner_v4_psk
* database_secret_key

Example Output known parameters from the endpoint:

```
curl -s https://quay.example.com/api/v1/superuser/config -H "Authorization: Bearer ..." | jq -r .config 

{
  "SESSION_COOKIE_SECURE": true,
  "PREFERRED_URL_SCHEME": "https",
...
  "ALLOW_PULLS_WITHOUT_STRICT_LOGGING": true,
  "AUTHENTICATION_TYPE": "LDAP",
  "AVATAR_KIND": "local",
  "BLACKLISTED_EMAIL_DOMAINS": [],
  "BLACKLIST_V2_SPEC": "<1.6.0",
  "BRANDING": {
    "logo": "/static/img/RH_Logo_Quay_Black_UX-horizontal.svg",
    "footer_img": "/static/img/RedHat.svg",
    "footer_url": "https://access.redhat.com/documentation/en-us/red_hat_quay/3/"
  },
  "BROWSER_API_CALLS_XHR_ONLY": false,
  "BUILDLOGS_REDIS": {
    "host": "redis",
    "password": "******** (8)",
    "port": 6379
  },
  "CLEAN_BLOB_UPLOAD_FOLDER": true,
  "CONTACT_INFO": [],
  "CORS_ORIGIN": "*",
  "CREATE_NAMESPACE_ON_PUSH": true,
  "CREATE_PRIVATE_REPO_ON_PUSH": true,
  "DB_CONNECTION_ARGS": {
    "max_connections": 30,
    "autorollback": true,
    "stale_timeout": 300,
    "keepalives": 1,
    "keepalives_idle": 10,
    "keepalives_interval": 2,
    "keepalives_count": 3,
    "tcp_user_timeout": 1000
  },
  "DB_URI": "********** (185)",
  "DEFAULT_SYSTEM_REJECT_QUOTA_BYTES": 0,
  "DEFAULT_TAG_EXPIRATION": "2w",
  "DISTRIBUTED_STORAGE_CONFIG": {
    "default": [
      "RadosGWStorage",
      {
        "access_key": "********** (20)",
        "bucket_name": "quay-registry",
        "hostname": "s3.example.com",
        "is_secure": true,
        "port": 443,
        "secret_key": "********** (40)",
        "storage_path": "/datastorage/registry",
        "region_name": "us-east-1"
      }
    ]
  },
  "DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS": [
    "default"
  ],
  "DISTRIBUTED_STORAGE_PREFERENCE": [
    "default"
  ],
  "DOCUMENTATION_ROOT": "https://access.redhat.com/documentation/en-us/red_hat_quay/3/",
  "ENABLE_HEALTH_DEBUG_SECRET": "******** (8)",
  "ENTITLEMENT_RECONCILIATION_MARKETPLACE_ENDPOINT": "",
  "ENTITLEMENT_RECONCILIATION_USER_ENDPOINT": "",
  "EXPIRED_APP_SPECIFIC_TOKEN_GC": "1d",
  "EXPORT_COMPLIANCE_ENDPOINT": "",
  "EXTERNAL_TLS_TERMINATION": true,
  "FEATURE_ACTION_LOG_ROTATION": false,
  "FEATURE_ADVERTISE_V2": true,
  "FEATURE_AGGREGATED_LOG_COUNT_RETRIEVAL": true,
  "FEATURE_ANONYMOUS_ACCESS": true,
  "FEATURE_APP_SPECIFIC_TOKENS": true,
  "FEATURE_AUTO_PRUNE": false,
  "FEATURE_BITBUCKET_BUILD": false,
  "FEATURE_BLACKLISTED_EMAILS": false,
  "FEATURE_BUILD_SUPPORT": false,
  "FEATURE_CHANGE_TAG_EXPIRATION": true,
  "FEATURE_DIRECT_LOGIN": true,
  "FEATURE_ENTITLEMENT_RECONCILIATION": false,
  "FEATURE_EXPORT_COMPLIANCE": false,
  "FEATURE_EXTENDED_REPOSITORY_NAMES": true,
  "FEATURE_FIPS": false,
  "FEATURE_GARBAGE_COLLECTION": true,
  "FEATURE_GITHUB_BUILD": false,
  "FEATURE_GITHUB_LOGIN": false,
  "FEATURE_GITLAB_BUILD": false,
  "FEATURE_GOOGLE_LOGIN": false,
  "FEATURE_INVITE_ONLY_USER_CREATION": false,
  "FEATURE_LIBRARY_SUPPORT": true,
  "FEATURE_LOG_EXPORT": true,
  "FEATURE_MAILING": false,
  "FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP": false,
  "FEATURE_PARTIAL_USER_AUTOCOMPLETE": true,
  "FEATURE_PERMANENT_SESSIONS": true,
  "FEATURE_PROXY_CACHE": true,
...
```

Example Output unknown parameters from the endpoint:
```
$ curl -s https://quay.example.com/api/v1/superuser/config -H "Authorization: Bearer ..." | jq -r '.warning'
{
  "DEBUG": false,
  "TESTING": false,
  "PROPAGATE_EXCEPTIONS": true,
  "SECRET_KEY": "********** (36)",
  "USE_X_SENDFILE": false,
  "APPLICATION_ROOT": "/",
  "SESSION_COOKIE_NAME": "_csrf_token",
  "SESSION_COOKIE_HTTPONLY": true,
  "SESSION_COOKIE_SAMESITE": "Lax",
  "SESSION_REFRESH_EACH_REQUEST": true,
  "SEND_FILE_MAX_AGE_DEFAULT": 0,
  "TRAP_HTTP_EXCEPTIONS": false,
  "EXPLAIN_TEMPLATE_LOADING": false,
  "MAX_COOKIE_SIZE": 4093,
  "ACCOUNT_RECOVERY_MODE": false,
  "ANALYTICS_TYPE": "FakeAnalytics",
...
```

Example Output Environment variables from the endpoint:
```
$ curl -s https://quay.example.com/api/v1/superuser/config -H "Authorization: Bearer ..." | jq -r '.env'
{
  "REDIS_PORT_6379_TCP_PROTO": "tcp",
  "PYTHONUNBUFFERED": "1",
  "LC_ALL": "C.UTF-8",
  "REDIS_PORT": "tcp://172.31.223.51:6379",
  "IGNORE_VALIDATION": "True",
  "WORKER_COUNT_SECSCAN": "1",
  "QUAY_PORT_8080_TCP_PORT": "8080",
  "DB_CONNECTION_POOLING": "true",
  "LANG": "C.UTF-8",
  "TZ": "UTC",
  "WORKER_COUNT_REGISTRY": "10",
  "HOSTNAME": "quay-5bf8bd7575-7824q",
  "QUAYDIR": "/quay-registry",
  "REDIS_PORT_6379_TCP_ADDR": "172.31.223.51",
  "QUAYCONF": "/quay-registry/conf",
  "REDIS_PORT_6379_TCP": "tcp://172.31.223.51:6379",
  "DB_CONNECTION_POOLING_REGISTRY": "true",
  "QUAY_SERVICE_HOST": "172.31.109.228",
  "QUAY_PORT_9091_TCP_PROTO": "tcp",
  "REDIS_SERVICE_PORT": "6379",
  "PYTHONIOENCODING": "UTF-8",
  "KUBERNETES_PORT_443_TCP_PROTO": "tcp",
  "KUBERNETES_PORT_443_TCP_ADDR": "172.31.0.1",
  "container": "oci",
  "QUAYPATH": "/quay-registry",
  "QUAY_PORT_9091_TCP_ADDR": "172.31.109.228",
  "USERS_DEBUG": "0",
  "QUAY_CONFIG_READ_ONLY_FIELD_GROUPS": "\"\"",
  "KUBERNETES_PORT": "tcp://172.31.0.1:443",
  "QUAY_SERVICE_PORT_HTTP_8080": "8080",
  "QUAY_PORT_8080_TCP": "tcp://172.31.109.228:8080",
  "PWD": "/quay-registry",
  "QUAY_PORT_8080_TCP_ADDR": "172.31.109.228",
  "QUAY_PORT_8080_TCP_PROTO": "tcp",
  "HOME": "/",
  "QUAY_SERVICE_PORT_HTTP_9091": "9091",
  "REDIS_SERVICE_PORT_REDIS": "6379",
  "RED_HAT_QUAY": "true",
  "KUBERNETES_SERVICE_PORT_HTTPS": "443",
  "REDIS_SERVICE_HOST": "172.31.223.51",
  "KUBERNETES_PORT_443_TCP_PORT": "443",
  "KUBERNETES_PORT_443_TCP": "tcp://172.31.0.1:443",
  "REDIS_PORT_6379_TCP_PORT": "6379",
  "DEBUGLOG": "true",
  "USERS_DEBUG": "0",
  ...
```

2024-09-24 14:17 UTC, michaelalang commented
The cypress test failing is not related to the change commited ...

```
  │ ✖  repository-autopruning.cy.ts             01:03       14       13        1        -        - │
```

2024-09-24 14:43 UTC, ibazulic commented
Why not modify the `/config` endpoint that exists for the same reason? This is not a super user thing.

https://github.com/quay/quay/blob/3181dfc93ef3ca9133635d67fdabe2d1e8456935/endpoints/web.py#L1107

2024-09-24 15:06 UTC, michaelalang commented
Quote: Why not modify the `/config` endpoint that exists for the same reason? This is not a super user thing.

Because it should be a protected endpoint and only available to SuperUsers ... Had that initially with /v1/config but as obviously seen, to sensitive to be available unprotected ...

2024-09-24 15:09 UTC, ibazulic commented
It cannot be a protected endpoint because the UI depends on it:

https://github.com/quay/quay/blob/3181dfc93ef3ca9133635d67fdabe2d1e8456935/web/src/resources/QuayConfig.ts#L7

Super user endpoints are protected with superuser authentication.

2024-09-24 15:24 UTC, michaelalang commented
Sure ... here's the original `/config`

```
$ curl -s  https://quay.example.com/config | jq -r 
{
  "account_recovery_mode": false,
  "config": {
    "AUTHENTICATION_TYPE": "LDAP",
    "AVATAR_KIND": "local",
    "BRANDING": {
      "footer_img": "/static/img/RedHat.svg",
      "footer_url": "https://access.redhat.com/documentation/en-us/red_hat_quay/3/",
      "logo": "/static/img/RH_Logo_Quay_Black_UX-horizontal.svg"
    },
    "CHANNEL_COLORS": [
      "#969696",
      "#aec7e8",
      "#ff7f0e",
      "#ffbb78",
      "#2ca02c",
      "#98df8a",
      "#d62728",
      "#ff9896",
      "#9467bd",
      "#c5b0d5",
      "#8c564b",
      "#c49c94",
      "#e377c2",
      "#f7b6d2",
      "#7f7f7f",
      "#c7c7c7",
      "#bcbd22",
      "#1f77b4",
      "#17becf",
      "#9edae5",
      "#393b79",
      "#5254a3",
      "#6b6ecf",
      "#9c9ede",
      "#9ecae1",
      "#31a354",
      "#b5cf6b",
      "#a1d99b",
      "#8c6d31",
      "#ad494a",
      "#e7ba52",
      "#a55194"
    ],
    "CONTACT_INFO": [],
    "DEBUG": false,
    "DOCUMENTATION_ROOT": "https://access.redhat.com/documentation/en-us/red_hat_quay/3/",
    "FEATURE_PROXY_CACHE": true,
    "FEATURE_QUOTA_MANAGEMENT": true,
    "FEATURE_REPO_MIRROR": true,
    "LOCAL_OAUTH_HANDLER": "/oauth/localapp",
    "PERMANENTLY_DELETE_TAGS": false,
    "PREFERRED_URL_SCHEME": "https",
    "QUOTA_BACKFILL": true,
    "RECAPTCHA_SITE_KEY": null,
    "REGISTRY_TITLE": "Example Container Registry",
    "REGISTRY_TITLE_SHORT": "Example",
    "SEARCH_MAX_RESULT_PAGE_COUNT": 10,
    "SEARCH_RESULTS_PER_PAGE": 10,
    "SENTRY_PUBLIC_DSN": null,
    "SERVER_HOSTNAME": "quay.example.com",
    "SETUP_COMPLETE": true,
    "STATIC_SITE_BUCKET": null,
    "TAG_EXPIRATION_OPTIONS": [
      "0s",
      "1d",
      "1w",
      "2w",
      "4w"
    ],
    "TERMS_OF_SERVICE_URL": "",
    "UI_DELAY_AFTER_WRITE_SECONDS": 3,
    "UI_V2_FEEDBACK_FORM": "https://7qdvkuo9rkj.typeform.com/to/XH5YE79P"
  },
  "external_login": [
    {
      "config": {
        "CLIENT_ID": "Home",
        "OIDC": true
      },
      "icon": "fa-user-circle",
      "id": "Example",
      "title": "Example"
    }
  ],
  "features": {
    "ACI_CONVERSION": false,
    "ACTION_LOG_ROTATION": false,
    "ADVERTISE_V2": true,
    "AGGREGATED_LOG_COUNT_RETRIEVAL": true,
    "ANONYMOUS_ACCESS": true,
    "APP_REGISTRY": false,
    "APP_SPECIFIC_TOKENS": true,
    "AUTO_PRUNE": false,
    "BILLING": false,
    "BITBUCKET_BUILD": false,
    "BLACKLISTED_EMAILS": false,
    "BUILD_SUPPORT": false,
    "CHANGE_TAG_EXPIRATION": true,
    "CLEAR_EXPIRED_RAC_ENTRIES": false,
    "DIRECT_LOGIN": true,
    "DISABLE_PULL_LOGS_FOR_FREE_NAMESPACES": false,
    "ENTITLEMENT_RECONCILIATION": false,
    "EXPORT_COMPLIANCE": false,
    "EXTENDED_REPOSITORY_NAMES": true,
    "FIPS": false,
    "FULL_CONFIG_SHOW": true,
    "GARBAGE_COLLECTION": true,
    "GENERAL_OCI_SUPPORT": true,
    "GITHUB_BUILD": false,
    "GITHUB_LOGIN": false,
    "GITLAB_BUILD": false,
    "GOOGLE_LOGIN": false,
    "HELM_OCI_SUPPORT": true,
    "INVITE_ONLY_USER_CREATION": false,
    "LIBRARY_SUPPORT": true,
    "LOG_EXPORT": true,
    "MAILING": false,
    "MANIFEST_SIZE_BACKFILL": true,
    "NAMESPACE_GARBAGE_COLLECTION": true,
    "NONSUPERUSER_TEAM_SYNCING_SETUP": false,
    "PARTIAL_USER_AUTOCOMPLETE": true,
    "PERMANENT_SESSIONS": true,
    "PROXY_CACHE": true,
    "PROXY_STORAGE": true,
    "PUBLIC_CATALOG": false,
    "QUOTA_MANAGEMENT": true,
    "RATE_LIMITS": false,
    "READER_BUILD_LOGS": false,
    "RECAPTCHA": false,
    "REPOSITORY_ACTION_COUNTER": true,
    "REPOSITORY_GARBAGE_COLLECTION": true,
    "REPO_MIRROR": true,
    "REQUIRE_ENCRYPTED_BASIC_AUTH": false,
    "REQUIRE_TEAM_INVITE": true,
    "RESTRICTED_USERS": false,
    "RESTRICTED_V1_PUSH": true,
    "RH_MARKETPLACE": false,
    "SECURITY_NOTIFICATIONS": true,
    "SECURITY_SCANNER": false,
    "SECURITY_SCANNER_NOTIFY_ON_NEW_INDEX": true,
    "SIGNING": false,
    "STORAGE_REPLICATION": false,
    "SUPERUSERS_FULL_ACCESS": true,
    "SUPERUSERS_ORG_CREATION_ONLY": false,
    "SUPER_USERS": true,
    "TEAM_SYNCING": true,
    "UI_DELAY_AFTER_WRITE": false,
    "UI_V2": true,
    "UI_V2_REPO_SETTINGS": true,
    "USERNAME_CONFIRMATION": false,
    "USER_CREATION": true,
    "USER_INITIALIZE": false,
    "USER_LAST_ACCESSED": true,
    "USER_LOG_ACCESS": false,
    "USER_METADATA": false,
    "USER_RENAME": false
  },
  "oauth": {
    "GITHUB_TRIGGER_CONFIG": {
      "AUTHORIZE_ENDPOINT": "https://github.com/login/oauth/authorize",
      "CLIENT_ID": null,
      "GITHUB_ENDPOINT": "https://github.com",
      "ORG_RESTRICT": false
    },
    "GITLAB_TRIGGER_CONFIG": {
      "AUTHORIZE_ENDPOINT": "https://gitlab.com/oauth/authorize",
      "CLIENT_ID": null,
      "GITLAB_ENDPOINT": "https://gitlab.com"
    }
  },
  "registry_state": "normal"
}
```

2024-09-24 15:28 UTC, michaelalang commented
and here's the full output of the `/api/v1/superuser/config` endpoint
```
{
  "config": {
    "SESSION_COOKIE_SECURE": true,
    "PREFERRED_URL_SCHEME": "https",
    "ACTION_LOG_ARCHIVE_LOCATION": "local_us",
    "ACTION_LOG_ARCHIVE_PATH": "actionlogarchive/",
    "ACTION_LOG_AUDIT_LOGINS": true,
    "ACTION_LOG_ROTATION_THRESHOLD": "30d",
    "ALLOWED_OCI_ARTIFACT_TYPES": {
      "application/vnd.oci.image.config.v1+json": [
        "application/vnd.dev.cosign.simplesigning.v1+json",
        "application/vnd.dsse.envelope.v1+json",
        "text/spdx",
        "text/spdx+xml",
        "text/spdx+json",
        "application/vnd.syft+json",
        "application/vnd.cyclonedx",
        "application/vnd.cyclonedx+xml",
        "application/vnd.cyclonedx+json",
        "application/vnd.in-toto+json"
      ],
      "application/vnd.cncf.helm.config.v1+json": [
        "application/tar+gzip",
        "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
      ],
      "application/vnd.oci.source.image.config.v1+json": [
        "application/vnd.oci.image.layer.v1.tar+gzip"
      ],
      "application/vnd.unknown.config.v1+json": [
        "application/vnd.cncf.openpolicyagent.policy.layer.v1+rego",
        "application/vnd.cncf.openpolicyagent.data.layer.v1+json"
      ]
    },
    "ALLOW_PULLS_WITHOUT_STRICT_LOGGING": true,
    "AUTHENTICATION_TYPE": "LDAP",
    "AVATAR_KIND": "local",
    "BLACKLISTED_EMAIL_DOMAINS": [],
    "BLACKLIST_V2_SPEC": "<1.6.0",
    "BRANDING": {
      "logo": "/static/img/RH_Logo_Quay_Black_UX-horizontal.svg",
      "footer_img": "/static/img/RedHat.svg",
      "footer_url": "https://access.redhat.com/documentation/en-us/red_hat_quay/3/"
    },
    "BROWSER_API_CALLS_XHR_ONLY": false,
    "BUILDLOGS_REDIS": {
      "host": "redis",
      "password": "******** (8)",
      "port": 6379
    },
    "CLEAN_BLOB_UPLOAD_FOLDER": true,
    "CONTACT_INFO": [],
    "CORS_ORIGIN": "*",
    "CREATE_NAMESPACE_ON_PUSH": true,
    "CREATE_PRIVATE_REPO_ON_PUSH": true,
    "DB_CONNECTION_ARGS": {
      "max_connections": 30,
      "autorollback": true,
      "stale_timeout": 300,
      "keepalives": 1,
      "keepalives_idle": 10,
      "keepalives_interval": 2,
      "keepalives_count": 3,
      "tcp_user_timeout": 1000
    },
    "DB_URI": "********** (185)",
    "DEFAULT_SYSTEM_REJECT_QUOTA_BYTES": 0,
    "DEFAULT_TAG_EXPIRATION": "2w",
    "DIRECT_OAUTH_CLIENTID_WHITELIST": [],
    "DISTRIBUTED_STORAGE_CONFIG": {
      "default": [
        "RadosGWStorage",
        {
          "access_key": "********** (20)",
          "bucket_name": "quay-registry",
          "hostname": "s3.example.com",
          "is_secure": true,
          "port": 443,
          "secret_key": "********** (40)",
          "storage_path": "/datastorage/registry",
          "region_name": "us-east-1"
        }
      ]
    },
    "DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS": [
      "default"
    ],
    "DISTRIBUTED_STORAGE_PREFERENCE": [
      "default"
    ],
    "DOCUMENTATION_ROOT": "https://access.redhat.com/documentation/en-us/red_hat_quay/3/",
    "ENABLE_HEALTH_DEBUG_SECRET": "******** (8)",
    "ENTITLEMENT_RECONCILIATION_MARKETPLACE_ENDPOINT": "",
    "ENTITLEMENT_RECONCILIATION_USER_ENDPOINT": "",
    "EXPIRED_APP_SPECIFIC_TOKEN_GC": "1d",
    "EXPORT_COMPLIANCE_ENDPOINT": "",
    "EXTERNAL_TLS_TERMINATION": true,
    "FEATURE_ACTION_LOG_ROTATION": false,
    "FEATURE_ADVERTISE_V2": true,
    "FEATURE_AGGREGATED_LOG_COUNT_RETRIEVAL": true,
    "FEATURE_ANONYMOUS_ACCESS": true,
    "FEATURE_APP_SPECIFIC_TOKENS": true,
    "FEATURE_AUTO_PRUNE": false,
    "FEATURE_BITBUCKET_BUILD": false,
    "FEATURE_BLACKLISTED_EMAILS": false,
    "FEATURE_BUILD_SUPPORT": false,
    "FEATURE_CHANGE_TAG_EXPIRATION": true,
    "FEATURE_DIRECT_LOGIN": true,
    "FEATURE_ENTITLEMENT_RECONCILIATION": false,
    "FEATURE_EXPORT_COMPLIANCE": false,
    "FEATURE_EXTENDED_REPOSITORY_NAMES": true,
    "FEATURE_FIPS": false,
    "FEATURE_GARBAGE_COLLECTION": true,
    "FEATURE_GITHUB_BUILD": false,
    "FEATURE_GITHUB_LOGIN": false,
    "FEATURE_GITLAB_BUILD": false,
    "FEATURE_GOOGLE_LOGIN": false,
    "FEATURE_INVITE_ONLY_USER_CREATION": false,
    "FEATURE_LIBRARY_SUPPORT": true,
    "FEATURE_LOG_EXPORT": true,
    "FEATURE_MAILING": false,
    "FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP": false,
    "FEATURE_PARTIAL_USER_AUTOCOMPLETE": true,
    "FEATURE_PERMANENT_SESSIONS": true,
    "FEATURE_PROXY_CACHE": true,
    "FEATURE_PROXY_STORAGE": true,
    "FEATURE_PUBLIC_CATALOG": false,
    "FEATURE_QUOTA_MANAGEMENT": true,
    "FEATURE_RATE_LIMITS": false,
    "FEATURE_READER_BUILD_LOGS": false,
    "FEATURE_RECAPTCHA": false,
    "FEATURE_REPO_MIRROR": true,
    "FEATURE_REQUIRE_ENCRYPTED_BASIC_AUTH": false,
    "FEATURE_REQUIRE_TEAM_INVITE": true,
    "FEATURE_RESTRICTED_USERS": false,
    "FEATURE_RESTRICTED_V1_PUSH": true,
    "FEATURE_SECURITY_NOTIFICATIONS": true,
    "FEATURE_SECURITY_SCANNER": false,
    "FEATURE_SECURITY_SCANNER_NOTIFY_ON_NEW_INDEX": true,
    "FEATURE_STORAGE_REPLICATION": false,
    "FEATURE_SUPERUSERS_FULL_ACCESS": true,
    "FEATURE_SUPERUSERS_ORG_CREATION_ONLY": false,
    "FEATURE_SUPER_USERS": true,
    "FEATURE_TEAM_SYNCING": true,
    "FEATURE_UI_DELAY_AFTER_WRITE": false,
    "FEATURE_UI_V2": true,
    "FEATURE_UI_V2_REPO_SETTINGS": true,
    "FEATURE_USERNAME_CONFIRMATION": false,
    "FEATURE_USER_CREATION": true,
    "FEATURE_USER_INITIALIZE": false,
    "FEATURE_USER_LAST_ACCESSED": true,
    "FEATURE_USER_LOG_ACCESS": false,
    "FEATURE_USER_METADATA": false,
    "FEATURE_USER_RENAME": false,
    "FRESH_LOGIN_TIMEOUT": "10m",
    "GITHUB_LOGIN_CONFIG": {},
    "GITHUB_TRIGGER_CONFIG": {},
    "GLOBAL_READONLY_SUPER_USERS": [],
    "HEALTH_CHECKER": [
      "LDAPHealthCheck",
      {}
    ],
    "LOGS_MODEL": "database",
    "LOGS_MODEL_CONFIG": {
      "should_skip_logging": null
    },
    "LOG_ARCHIVE_LOCATION": "default",
    "LOG_ARCHIVE_PATH": "logarchive/",
    "MAIL_DEFAULT_SENDER": "support@quay.io",
    "MAIL_PORT": 587,
    "MAIL_SERVER": "",
    "MAIL_USE_TLS": false,
    "MAXIMUM_LAYER_SIZE": "20G",
    "PERMANENTLY_DELETE_TAGS": false,
    "PROMETHEUS_NAMESPACE": "quay",
    "PUBLIC_NAMESPACES": [],
    "QUOTA_BACKFILL": true,
    "QUOTA_INVALIDATE_TOTALS": true,
    "QUOTA_TOTAL_DELAY_SECONDS": 1800,
    "RECAPTCHA_WHITELISTED_USERS": [],
    "REGISTRY_STATE": "normal",
    "REGISTRY_TITLE": "Example Container Registry",
    "REGISTRY_TITLE_SHORT": "Example",
    "REPO_MIRROR_INTERVAL": 30,
    "REPO_MIRROR_ROLLBACK": false,
    "REPO_MIRROR_TLS_VERIFY": true,
    "RESET_CHILD_MANIFEST_EXPIRATION": false,
    "ROBOTS_WHITELIST": [],
    "SEARCH_MAX_RESULT_PAGE_COUNT": 10,
    "SEARCH_RESULTS_PER_PAGE": 10,
    "SECURITY_SCANNER_INDEXING_INTERVAL": 30,
    "SECURITY_SCANNER_V4_ENDPOINT": "https://clair.example.com",
    "SECURITY_SCANNER_V4_MANIFEST_CLEANUP": true,
    "SECURITY_SCANNER_V4_PSK": "********** (20)",
    "SERVER_HOSTNAME": "quay.example.com",
    "SUCCESSIVE_TRIGGER_FAILURE_DISABLE_THRESHOLD": 100,
    "SUCCESSIVE_TRIGGER_INTERNAL_ERROR_DISABLE_THRESHOLD": 5,
    "SUPER_USERS": [],
    "TAG_EXPIRATION_OPTIONS": [
      "0s",
      "1d",
      "1w",
      "2w",
      "4w"
    ],
    "TEAM_RESYNC_STALE_TIME": "6h",
    "TERMS_OF_SERVICE_URL": "",
    "UI_DELAY_AFTER_WRITE_SECONDS": 3,
    "UI_V2_FEEDBACK_FORM": "https://7qdvkuo9rkj.typeform.com/to/XH5YE79P",
    "USERFILES_LOCATION": "default",
    "USERFILES_PATH": "userfiles/",
    "USER_EVENTS_REDIS": {
      "host": "redis",
      "password": "******** (8)",
      "port": 6379
    },
    "USER_RECOVERY_TOKEN_LIFETIME": "30m",
    "V1_PUSH_WHITELIST": [],
    "V2_PAGINATION_SIZE": 50,
    "WEBHOOK_HOSTNAME_BLACKLIST": []
  },
  "warning": {
    "DEBUG": false,
    "TESTING": false,
    "PROPAGATE_EXCEPTIONS": true,
    "SECRET_KEY": "********** (36)",
    "USE_X_SENDFILE": false,
    "APPLICATION_ROOT": "/",
    "SESSION_COOKIE_NAME": "_csrf_token",
    "SESSION_COOKIE_HT [...]

2024-09-24 15:39 UTC, ibazulic commented
Oh, I see, so much more data will be available to the administrator with this endpoint. Yeah, that does require it to be under a super suer API. Sounds good to me!

2024-09-24 15:39 UTC, ibazulic approved these changes

2024-09-24 15:40 UTC, michaelalang commented
@ibazulic thanks for checking in <3

2025-03-20 23:53 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +                    ):
How about defining these as a constant in this file?

2025-03-20 23:53 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +                    app.logger.error(f"Cannot parse config, error {procerr}")
There is a [logger](https://github.com/quay/quay/blob/master/endpoints/api/superuser.py#L63) defined in this file, you can use that here and on line 1368.

2025-03-20 23:53 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +                # but to ensure we do not raise an Exception
nit: we raise an exception

2025-03-20 23:53 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +                return dict(config=str(cfg), warning=str(warn), env=dict(os.environ))
why convert `cfg` and `warn` to string? Should the above try except catch any errors?

2025-03-20 23:55 UTC, Sunandadadi commented
The PR description mentions `schema` key is expected. I don't see it in the curl response or in the code.
Added a few other minor comments otherwise looks good. Can you also add a test to the endpoint?

2025-03-21 07:42 UTC, michaelalang commented on endpoints/api/superuser.py
> +                    ):
Hi @Sunandadadi  
yes I was thinking to get those separated into a file. Still I haven't found a good approach to get everyone implementing a new feature or changing one on catching up that those files/variables should be updated.
If you have any suggestion how we an achieve people noticing that that API exposes their possible secret if they do not update is highly appreciated <3

2025-03-21 07:43 UTC, michaelalang commented on endpoints/api/superuser.py
> +                    app.logger.error(f"Cannot parse config, error {procerr}")
sure

2025-03-21 07:45 UTC, michaelalang commented on endpoints/api/superuser.py
> +                # but to ensure we do not raise an Exception
I don't understand what yoou mean with that comment ...

2025-03-21 07:52 UTC, michaelalang commented on endpoints/api/superuser.py
> +                return dict(config=str(cfg), warning=str(warn), env=dict(os.environ))
In line with the previous comment (and mybe that helps understanding the logic).

we process dictionaries with possible sub dictionaries / arrays and any item in those iterable might contain a function (typically those are the flask methods) ...

so that give as example
```
for key in iterable:
   iterable.get(key) # can be another iterable like dict/array 
```
and any of those sub iterable keys if being a function is not obfuscate able so we ignore it 
on the other exception handling of the method `process_config` the conversion to strings of the content of `cfg` and `warn` is done if there's any new method in those which is why we convert them to strings as otherwise the API call will break between version compared to `returning` in stringified json content.

Does this make more sense for you now ?

2025-03-21 07:58 UTC, michaelalang commented
> The PR description mentions `schema` key is expected. I don't see it in the curl response or in the code. Added a few other minor comments otherwise looks good. Can you also add a test to the endpoint?

ack ... good catch ...  will add the unittest accordingly

2025-03-21 13:29 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +                    ):
You can add a new feature flag something like `EXPOSE_CONFIG` and expose this endpoint if the feature is set to true.

2025-03-21 13:30 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +                # but to ensure we do not raise an Exception
Sorry, I read wrong. resolving the conversation.

2025-03-21 15:37 UTC, michaelalang commented on endpoints/api/superuser.py
> +                return dict(config=str(cfg), warning=str(warn), env=dict(os.environ))
sure ... so with
```
def process_config():
            for k, v in app.config.items():
                if not type(v) in (list, dict, tuple, int, str, bool):
                    continue
```
if any of the items would return a `class` for example ... than if the key isn't in the `obfuscate` list of verbs to be protected, it would return the content in the dict like
```
{ "somekey": <class ....>, ...}
```
if that type of class isn't serializable for json it would raise an exception instead it will return the `stringified` represenation of the complete dict.

```
>>> import json
>>> class Something():  pass
>>> json.dumps(dict(key1=1, key2="str", key3=Something()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Something is not JSON serializable
```

compared to 
```
>>> json.dumps(dict(key1=1, key2="str", key3=str(Something())))
'{"key1": 1, "key2": "str", "key3": "<__main__.Something object at 0x7f054eac0640>"}'
```

2025-03-23 23:40 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +                return dict(config=str(cfg), warning=str(warn), env=dict(os.environ))
I meant an example of a key where class is returned in value.

2025-03-24 06:11 UTC, michaelalang commented
@Sunandadadi I added the unittests as well anything else we need to get this rolling ?

2025-03-24 14:15 UTC, Sunandadadi commented
@michaelalang thank you for adding tests. Do you want to address [this](https://github.com/quay/quay/pull/3253#discussion_r2007021166) comment in this PR?

2025-03-24 15:12 UTC, michaelalang commented on endpoints/api/superuser.py
> +                return dict(config=str(cfg), warning=str(warn), env=dict(os.environ))
@Sunandadadi for example ..

```
oc -n quay exec -ti deploy/quay -- python
>>> import app
Failed to validate security scanner V4 configuration
>>> app.app.config["HTTPCLIENT"]
<requests.sessions.Session object at 0x7f30b261e070>
>>> app.app.config["LOGS_MODEL_CONFIG"]
{'should_skip_logging': <function configure.<locals>.should_skip_logging at 0x7f30b0fa51f0>}
>>>
```

2025-03-25 09:51 UTC, michaelalang commented
> @michaelalang thank you for adding tests. Do you want to address [this](https://github.com/quay/quay/pull/3253#discussion_r2007021166) comment in this PR?

@Sunandadadi added the feature flag accordingly. Had to rebase as config.py was in conflict.

2025-03-26 05:14 UTC, michaelalang commented
@Sunandadadi should be working now as expected with:

* Feature Flag
* unitttests
* and the missing schema output 

please note that the schema update PR is necessary to have all featues included ...

2025-04-08 01:11 UTC, Sunandadadi requested changes
Sorry for the delay on this. Added one minor comment otherwise everything looks good. Thank you for adding tests.

2025-04-08 01:11 UTC, Sunandadadi commented on endpoints/api/superuser.py
> +class SuperUserDumpConfig(ApiResource):
You can add another decorator here for `features.SUPERUSER_CONFIGDUMP` and remove [here](https://github.com/quay/quay/pull/3253/files#diff-e1fe16b0a62b4ced394eb81261f3f60d5086988f3e7be21489f6df00bbcd6d4eR1374).

2025-04-08 17:02 UTC, michaelalang commented on endpoints/api/superuser.py
> +class SuperUserDumpConfig(ApiResource):
@Sunandadadi no that doesn't work as other checks on in the unittest list are expecting to access that endpoint I tried and adding it afterwards was the best I was able to come up with ..

2025-04-08 19:07 UTC, Sunandadadi approved these changes
lgtm

2025-04-28 16:29 UTC, merged