wip: Add proxy cache config UI to org settings (PROJQUAY-7697)
quay/quay pull request #3388
Opened 2024-11-07 18:34 UTC by harishsurf

Adds proxy cache config UI to organization settings tab

![proxy-cache-config](https://github.com/user-attachments/assets/9d134d69-64db-45c7-80e5-760e8d6f09c2)

Todo:
- cypress test
- show proxy cache configuration during org creation (separate PR)

2024-11-22 19:01 UTC, bcaton85 requested changes
Overall looks good, functionally correct. There are a couple of bugs and additional tests are required but nothing major.

2024-11-25 10:02 UTC, harishsurf commented on web/src/resources/ProxyCacheResource.ts
> +  const proxyResponse = await axios.post(proxyCacheConfigUrl, proxyCacheConfig);
Hmm, for me it works fine when in incognito mode. In normal browser mode, these fields get autofilled and clearing them sets these fields to an empty string. I am not seeing an option to disable autofill on either `TextInput` or `Form` PF component. Hence, I have added the check for empty string in the above code right before `axios.post`

2024-11-25 13:41 UTC, harishsurf commented on web/src/routes/OrganizationsList/Organization/Tabs/Settings/Settings.tsx
> +      visible: quayConfig?.features?.PROXY_CACHE,
good catch! added a test

2024-11-26 14:11 UTC, bcaton85 commented on web/src/resources/ProxyCacheResource.ts
> +  const proxyResponse = await axios.post(proxyCacheConfigUrl, proxyCacheConfig);
okay makes sense. As long as there's a condition that if the fields are empty string they should be set to null when being sent in the request that should be fine

2024-11-26 15:59 UTC, bcaton85 approved these changes
LGTM - this will need to be cherrypicked into redhat-3.13

2024-11-27 02:24 UTC, harishsurf commented
/cherrypick redhat-3.13

2024-11-27 02:26 UTC, merged