Redis Model Cache
quay/quay pull request #444
Opened 2020-06-16 20:26 UTC by alecmerdler

### Description

Adds model cache implementation backed by Redis. 

### Performance Improvements

TODO(alecmerdler)

Addresses https://issues.redhat.com/browse/PROJQUAY-788

2021-04-10 23:25 UTC, alecmerdler commented
Rebased with `master`.

2021-04-11 03:36 UTC, kleesc reviewed
> When using this model cache implementation, the Redis dependency changes from being low priority (effectively ephemeral) to being critical (and should be HA).

It depends. Most deployment aren't large enough or don't generate enough traffic to cause a thundering herd issue, and clearing the cache wouldn't be an issue.

2021-04-11 03:36 UTC, kleesc commented on data/cache/impl.py
> +                if cached_result != not_found:
Not specific to this implementation, but we could instrument this to measure the hit rate.
e.g A `Counter` metrics for  cache hits divided by a `Counter` metrics for `retrieve` calls

2021-04-12 17:09 UTC, kleesc commented
@alecmerdler The current ticket linked is the wrong one. It should be PROJQUAY-788

2021-04-13 13:59 UTC, kleesc commented on data/cache/impl.py
> +            "single_connection_client": True,
I _think_ StrictRedis already uses a connection pool under the hood.

2021-04-13 20:14 UTC, alecmerdler commented on data/cache/impl.py
> +cache_retrieves = Counter(
@kleesc What do you think of these metrics?

2021-04-13 23:09 UTC, kleesc commented
@alecmerdler Like you previously mentioned, I think we should make it so that two requests can't write to the same key at once (grab a Lock).

2021-04-14 18:53 UTC, alecmerdler commented
@kleesc Ready for another review after being rebased with the `GlobalLock` fix.

2021-04-14 19:23 UTC, kleesc requested changes

2021-04-14 19:23 UTC, kleesc commented on data/cache/impl.py
> +                except LockNotAcquiredException:
I'm not sure if this is going to catch it. I think the GlobalLock context manager needs to be inside the try block.

2021-04-14 19:26 UTC, kleesc requested changes

2021-04-14 19:26 UTC, kleesc commented on data/cache/impl.py
> +            with GlobalLock(cache_key.key, lock_ttl=5):
The key will need to be different from the actual key. Maybe add a `LOCK_` prefix or suffix.

2021-04-15 15:07 UTC, kleesc submitted a review, later dismissed
LGTM

2021-04-15 15:19 UTC, alecmerdler commented
I'm seeing slow pushes (stuck in `preparing` state) when running this on my k8s cluster. Going to do a bit more testing to ensure it's unrelated to this code change.

2021-04-15 16:51 UTC, kleesc approved these changes
LGTM

2021-04-15 17:31 UTC, merged