[WIP] Replace jwkest with authlib
quay/quay pull request #685
Opened 2021-03-02 18:07 UTC by kleesc

**Issue:** https://issues.redhat.com/browse/PROJQUAY-224

**Changelog:** 
- Replaces jwkest (depends on `PyCrypto`) with authlib (supports multiple backends, including `cryptography`) 

**Docs:** 

**Testing:** 

**Details:**

2021-03-04 04:38 UTC, lepture commented
@kleesc Authlib has an alpha 1.0.0 release, which support generate key natively. https://docs.authlib.org/en/latest/specs/rfc7517.html#authlib.jose.JsonWebKey.generate_key

2021-03-11 15:05 UTC, thomasmckay requested changes

2021-03-11 15:05 UTC, thomasmckay commented on boot.py
> +                    format=serialization.PrivateFormat.TraditionalOpenSSL,
missing `from cryptography.hazmat.primitives import serialization`

2021-03-12 12:38 UTC, thomasmckay requested changes

2021-03-12 12:38 UTC, thomasmckay commented on requirements-osbs.txt
> +moto==2.0.1
Remove this as it tries to bring in other deps and we don't need it at runtime. I've created PROJQUAY-1720 to track revisiting all the packages.

2021-03-15 17:41 UTC, thomasmckay approved these changes
LGTM

2021-03-15 19:25 UTC, merged