mirror: Add feature flag to allow initial user creation (PROJQUAY-1926)
quay/quay pull request #792
Opened 2021-05-16 00:18 UTC by jonathankingfc

- Users can use FEATURE_INIT_USER to allow an initial user to be created.
- Credentials can be passed through `INIT_USERNAME` and `INIT_PASSWORD` otherwise defaults will be used

2021-05-17 05:16 UTC, LiZhang19817 commented
Will this feature "FEATURE_INIT_USER" be exposed on quay config editor?

2021-05-17 05:28 UTC, alecmerdler commented
Agreed with @LiZhang19817, this PR should be accompanied by a subsequent PR to `config-tool`.

2021-05-17 05:28 UTC, alecmerdler commented on Makefile
> +	docker-compose up  --build -d redis
Can you explain what this does?

2021-05-17 05:33 UTC, alecmerdler commented on local-dev/stack/config.yaml
> -FEATURE_SECURITY_SCANNER: true
Is disabling the security scanner by default an intended part of this PR?

2021-05-17 05:34 UTC, alecmerdler commented on local-dev/stack/config.yaml
> +FEATURE_INIT_USER: true
Prefer `FEATURE_INITIAL_USER`, `INITIAL USERNAME`, and `INITIAL_PASSWORD`.

2021-05-17 05:38 UTC, alecmerdler requested changes
This deserves further discussion as it involves database rows defined by `config.yaml`. 

- What happens if this user is deleted? When Quay restarts, is the user recreated?
- Should there be the same password requirements on the initial user password as on the rest of Quay's users? Will that cause issues if they are different?
- What happens if the `config.yaml` is modified to remove this initial user, but it exists previously? Is it deleted?

2021-05-17 05:40 UTC, alecmerdler commented
I think this is significant enough of a feature to deserve an [enhancement proposal](https://github.com/quay/enhancements), especially to capture the motivations and design.

2021-05-17 14:09 UTC, kleesc requested changes

2021-05-17 14:09 UTC, kleesc commented on data/model/user.py
> +    if bool(list(User.select().limit(1))):
We've generally favored running the query and catching the "DoesNotExist" exception when testing for existence.
e.g 
```
try:
  User.select().limit(1).get()
except UserDoesNotExist:
  logger.debug("Cannot initialize user in a non-empty database")
  return
```

2021-05-17 14:09 UTC, kleesc commented on data/model/user.py
> +def create_init_user(
Can we add a test for this? Just to test the new constraints we're adding to `create_user`.

2021-05-17 14:09 UTC, kleesc commented
@jonathankingfc Is this a duplicate of #771 ?

2021-05-17 17:12 UTC, kleesc commented
> I think this is significant enough of a feature to deserve an [enhancement proposal](https://github.com/quay/enhancements), especially to capture the motivations and design.

@alecmerdler @jonathankingfc Agree. I'm not sure what the scope of this needs to be. Are we just looking to get access to the registry API, or also to Quay's API. AFAIK the latter also requires an application/org to be able to create an oauth token to be able to use on behalf of that first user.

2021-06-28 16:19 UTC, jonathankingfc commented
Closing in favor of https://github.com/quay/quay/pull/771

2021-06-28 16:19 UTC, jonathankingfc commented
Closing in favor of https://github.com/quay/quay/pull/771

2021-06-28 16:19 UTC, closed without merging