registry: add support for extended repository names (PROJQUAY-1535)
quay/quay pull request #814
Opened 2021-06-21 15:16 UTC by kleesc

Allows forward slashes to be used in repository names according to
https://docs.docker.com/docker-hub/repos/.

NOTE: This change simply allows the use of "/" in repository
names needed for certain Openshift use cases. This does not implement
any new permission model for nested paths. i.e A repository with a
nested path is treated as a single repository under a _single_
namespace.

2021-06-28 13:15 UTC, BillDett commented on util/names.py
> +    "^(?=.{0,255}$)[a-z0-9][\.a-z0-9_-]*(?:\/[a-z0-9][\.a-z0-9_-]*)*$"
@kleesc - should this be a raw string (r"...") as well like the REPOSITORY_NAME_REGEX?

2021-07-15 14:07 UTC, kleesc commented
@jonathankingfc @thomasmckay Ping

2021-07-15 16:46 UTC, thomasmckay requested changes

2021-07-15 16:46 UTC, thomasmckay commented on requirements.txt
> -zope.interface==4.7.1
Remove from requirements-osbs.txt as well

2021-07-23 17:43 UTC, jonathankingfc approved these changes

2021-07-28 14:11 UTC, jonathankingfc approved these changes

2021-07-28 15:42 UTC, jonathankingfc approved these changes

2021-07-28 15:44 UTC, thomasmckay approved these changes
LGTM

2021-07-28 16:27 UTC, merged